// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OpenHouse.Model.Core
{
    public partial class Property
    {
        public int PropertyId { get; set; }
        public int PropertyClassId { get; set; }
        public int? PropertyNum { get; set; }
        public string PropertySubNum { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string PostCode { get; set; }
        public DateTime? DemolitionDate { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual Propertyclass PropertyClass { get; set; }
    }
}