// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OpenHouse.Model.Core
{
    public partial class Propertyclass
    {
        public Propertyclass()
        {
            Property = new HashSet<Property>();
        }

        public int PropertyClassId { get; set; }
        public string PropertyClass1 { get; set; }

        public virtual ICollection<Property> Property { get; set; }
    }
}