// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public class PropertyViewModel
    {
        public PropertyViewModel()
        {
            propertynote = new HashSet<propertynote>();
        }

        [Required]
        public int propertyId { get; set; }
        [Required]
        [Display(Name = "Property Class")]
        public int propertyClassId { get; set; }
        [Required]
        [Display(Name = "Property Type")]
        public int? propertyTypeId { get; set; }
        [Required]
        [Display(Name = "Property Num")]
        public int? propertyNum { get; set; }
        [Display(Name = "Sub number")]
        public string propertySubNum { get; set; }
        [Required]
        [Display(Name = "Address 1")]
        public string address1 { get; set; }
        [Display(Name = "Address 2")]
        public string address2 { get; set; }
        [Display(Name = "Address 3")]
        public string address3 { get; set; }
        [Display(Name = "Address 4")]
        public string address4 { get; set; }
        [Required]
        [Display(Name = "Post Code")]
        public string postCode { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Demolition Date")]
        public DateTime? demolitionDate { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Creation Date")]
        public DateTime? creationDate { get; set; }
        [Required]
        [Display(Name = "Living Room Qty")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int? livingRoomQty { get; set; }
        [Required]
        [Display(Name = "Single Bedroom Qty")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int? singleBedroomQty { get; set; }
        [Required]
        [Display(Name = "Double Bedroom Qty")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int? doubleBedroomQty { get; set; }
        [Required]
        [Display(Name = "Max Occupants")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int? maxOccupants { get; set; }
        public int? tenancyId { get; set; }
        public string updatedByUserID { get; set; }
        public string updatedByUsername { get; set; }
        public DateTime updatedDT { get; set; }
        public string createdByUserID { get; set; }
        public string createdByUsername { get; set; }
        public DateTime createdDT { get; set; }


        public virtual propertyclass propertyClass { get; set; }
        public virtual propertytype propertyType { get; set; }
        public ICollection<propertynote> propertynote { get; set; }
        public ICollection<propertycharge> propertycharge { get; set; }
        public List<vwtenancy> tenancyHistory { get; set; }
    }
}