// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class action
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int actionId { get; set; }
        [Column(TypeName = "int(11)")]
        public int actionTypeId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int assignedUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime actionDueDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? actionCompletedDate { get; set; }
        [Column(TypeName = "int(11)")]
        public int updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Column(TypeName = "int(11)")]
        public int createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }

        [ForeignKey(nameof(actionTypeId))]
        [InverseProperty(nameof(actiontype.action))]
        public virtual actiontype actionType { get; set; }
        [ForeignKey(nameof(tenancyId))]
        [InverseProperty("action")]
        public virtual tenancy tenancy { get; set; }
    }
}