// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class alerttype
    {
        public alerttype()
        {
            alert = new HashSet<alert>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int alertTypeId { get; set; }
        [Column("alertType", TypeName = "varchar(100)")]
        public string alertType1 { get; set; }

        [InverseProperty("alertType")]
        public virtual ICollection<alert> alert { get; set; }
    }
}