// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class alert
    {
        public alert()
        {
            tenancyalert = new HashSet<tenancyalert>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int alertId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? alertTypeId { get; set; }
        [Column(TypeName = "text")]
        public string alertText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? startDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? endDT { get; set; }
        [Column(TypeName = "int(11)")]
        public int? updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updatedDT { get; set; }
        [Column(TypeName = "int(11)")]
        public int? createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createdDT { get; set; }

        [ForeignKey(nameof(alertTypeId))]
        [InverseProperty(nameof(alerttype.alert))]
        public virtual alerttype alertType { get; set; }
        [InverseProperty("alert")]
        public virtual ICollection<tenancyalert> tenancyalert { get; set; }
    }
}