// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class paymentsource
    {
        public paymentsource()
        {
            payment = new HashSet<payment>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int paymentSourceId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string source { get; set; }

        [InverseProperty("paymentSource")]
        public virtual ICollection<payment> payment { get; set; }
    }
}