// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class payment
    {
        public payment()
        {
            rentledger = new HashSet<rentledger>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int paymentId { get; set; }
        [Column(TypeName = "int(11)")]
        public int propertyChargeId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int paymentSourceId { get; set; }
        public float? amount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime paymentDT { get; set; }
        [Column(TypeName = "varchar(255)")]
        public string paymentProviderReference { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }

        [ForeignKey(nameof(paymentSourceId))]
        [InverseProperty(nameof(paymentsource.payment))]
        public virtual paymentsource paymentSource { get; set; }
        [ForeignKey(nameof(propertyChargeId))]
        [InverseProperty(nameof(propertycharge.payment))]
        public virtual propertycharge propertyCharge { get; set; }
        [ForeignKey(nameof(tenancyId))]
        [InverseProperty("payment")]
        public virtual tenancy tenancy { get; set; }
        [InverseProperty("payment")]
        public virtual ICollection<rentledger> rentledger { get; set; }
    }
}