// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class propertyclass
    {
        public propertyclass()
        {
            property = new HashSet<property>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int propertyClassId { get; set; }
        [Column("propertyClass", TypeName = "varchar(100)")]
        public string propertyClass1 { get; set; }

        [InverseProperty("propertyClass")]
        public virtual ICollection<property> property { get; set; }
    }
}