// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class propertytype
    {
        public propertytype()
        {
            property = new HashSet<property>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int propertyTypeId { get; set; }
        [Column("propertyType", TypeName = "varchar(100)")]
        public string propertyType1 { get; set; }

        [InverseProperty("propertyType")]
        public virtual ICollection<property> property { get; set; }
    }
}