// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class propertycharge
    {
        public propertycharge()
        {
            payment = new HashSet<payment>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int propertyChargeId { get; set; }
        [Column(TypeName = "int(11)")]
        public int propertyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int rentAccountId { get; set; }
        public float? charge { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime startDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? endDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }

        [ForeignKey(nameof(propertyId))]
        [InverseProperty("propertycharge")]
        public virtual property property { get; set; }
        [ForeignKey(nameof(rentAccountId))]
        [InverseProperty(nameof(rentaccount.propertycharge))]
        public virtual rentaccount rentAccount { get; set; }
        [InverseProperty("propertyCharge")]
        public virtual ICollection<payment> payment { get; set; }
    }
}