// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class relationship
    {
        public relationship()
        {
            tenancyhouseholdjointTenantRelationship = new HashSet<tenancyhousehold>();
            tenancyhouseholdleadTenantRelationship = new HashSet<tenancyhousehold>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int relationshipId { get; set; }
        [Column("relationship", TypeName = "varchar(100)")]
        public string relationship1 { get; set; }

        [InverseProperty(nameof(tenancyhousehold.jointTenantRelationship))]
        public virtual ICollection<tenancyhousehold> tenancyhouseholdjointTenantRelationship { get; set; }
        [InverseProperty(nameof(tenancyhousehold.leadTenantRelationship))]
        public virtual ICollection<tenancyhousehold> tenancyhouseholdleadTenantRelationship { get; set; }
    }
}