// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class tenancyalert
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int tenancyAlertId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int alertId { get; set; }

        [ForeignKey(nameof(alertId))]
        [InverseProperty("tenancyalert")]
        public virtual alert alert { get; set; }
        [ForeignKey(nameof(tenancyId))]
        [InverseProperty("tenancyalert")]
        public virtual tenancy tenancy { get; set; }
    }
}