// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class tenancynote
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int tenancyNoteId { get; set; }
        [Column(TypeName = "int(11)")]
        public int noteId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }

        [ForeignKey(nameof(noteId))]
        [InverseProperty("tenancynote")]
        public virtual note note { get; set; }
        [ForeignKey(nameof(tenancyId))]
        [InverseProperty("tenancynote")]
        public virtual tenancy tenancy { get; set; }
    }
}