// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class tenancyhousehold
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int tenancyHouseholdId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int personId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? leadTenantRelationshipId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? jointTenantRelationshipId { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }

        [ForeignKey(nameof(jointTenantRelationshipId))]
        [InverseProperty(nameof(relationship.tenancyhouseholdjointTenantRelationship))]
        public virtual relationship jointTenantRelationship { get; set; }
        [ForeignKey(nameof(leadTenantRelationshipId))]
        [InverseProperty(nameof(relationship.tenancyhouseholdleadTenantRelationship))]
        public virtual relationship leadTenantRelationship { get; set; }
        [ForeignKey(nameof(personId))]
        [InverseProperty("tenancyhousehold")]
        public virtual person person { get; set; }
        [ForeignKey(nameof(tenancyId))]
        [InverseProperty("tenancyhousehold")]
        public virtual tenancy tenancy { get; set; }
    }
}