// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class tenuretype
    {
        public tenuretype()
        {
            tenancy = new HashSet<tenancy>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int tenureTypeId { get; set; }
        [Column("tenureType", TypeName = "varchar(100)")]
        public string tenureType1 { get; set; }

        [InverseProperty("tenureType")]
        public virtual ICollection<tenancy> tenancy { get; set; }
    }
}