// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class title
    {
        public title()
        {
            person = new HashSet<person>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int titleId { get; set; }
        [Column("title", TypeName = "varchar(100)")]
        public string title1 { get; set; }

        [InverseProperty("title")]
        public virtual ICollection<person> person { get; set; }
    }
}