// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwaction
    {
        [Column(TypeName = "int(11)")]
        public int actionId { get; set; }
        [Column(TypeName = "int(11)")]
        public int actionTypeId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string actionType { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? propertyId { get; set; }
        [Column(TypeName = "text")]
        public string contactAddress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime actionDueDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? actionCompletedDate { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }
        [Column(TypeName = "int(11)")]
        public int assignedUserId { get; set; }
    }
}