// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwalert
    {
        [Column(TypeName = "int(11)")]
        public int tenancyAlertId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int alertId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? alertTypeId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string alerttype { get; set; }
        [Column(TypeName = "text")]
        public string alertText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? startDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? endDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "varchar(256)")]
        public string updateByUsername { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "varchar(256)")]
        public string createdByUsername { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }
    }
}