// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwproperty
    {
        [Column(TypeName = "int(11)")]
        public int propertyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int propertyClassId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string propertyClass { get; set; }
        [Column(TypeName = "int(11)")]
        public int? propertyTypeId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string propertyType { get; set; }
        [Column(TypeName = "int(11)")]
        public int? propertyNum { get; set; }
        [Column(TypeName = "varchar(5)")]
        public string propertySubNum { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string address1 { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string address2 { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string address3 { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string address4 { get; set; }
        [Column(TypeName = "varchar(8)")]
        public string postCode { get; set; }
        [Column(TypeName = "text")]
        public string contactAddress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? demolitionDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? creationDate { get; set; }
        [Column(TypeName = "int(11)")]
        public int? livingRoomQty { get; set; }
        [Column(TypeName = "int(11)")]
        public int? singleBedroomQty { get; set; }
        [Column(TypeName = "int(11)")]
        public int? doubleBedroomQty { get; set; }
        [Column(TypeName = "int(11)")]
        public int? maxOccupants { get; set; }
        [Column(TypeName = "int(11)")]
        public int? tenancyId { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }
    }
}