// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwrentledger
    {
        [Column(TypeName = "int(11)")]
        public int rentLedgerId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime periodStartDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime periodEndDT { get; set; }
        [Column(TypeName = "int(11)")]
        public int propertyChargeId { get; set; }
        public float? charge { get; set; }
        [Column(TypeName = "int(11)")]
        public int rentAccountId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string rentAccount { get; set; }
        [Column(TypeName = "int(11)")]
        public int? paymentId { get; set; }
        public float? amount { get; set; }
        [Column(TypeName = "int(11)")]
        public int? paymentSourceId { get; set; }
        [Column(TypeName = "varchar(255)")]
        public string paymentProviderReference { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? paymentDT { get; set; }
    }
}