// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwtenancyhousehold
    {
        [Column(TypeName = "int(11)")]
        public int tenancyHouseholdId { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int personId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string title { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string firstName { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string middleName { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string surname { get; set; }
        [Column(TypeName = "varchar(201)")]
        public string fullName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dateOfBirth { get; set; }
        [Column(TypeName = "varchar(20)")]
        public string telephone { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string email { get; set; }
        [Column(TypeName = "int(11)")]
        public int? nationalityId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string nationality { get; set; }
        [Column(TypeName = "int(11)")]
        public int? leadTenantRelationshipId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string relationshipToLeadTenant { get; set; }
        [Column(TypeName = "int(11)")]
        public int? jointTenantRelationshipId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string relationshipToJointTenant { get; set; }
    }
}