// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwtenancy
    {
        [Column(TypeName = "int(11)")]
        public int tenancyId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? propertyId { get; set; }
        [Column(TypeName = "text")]
        public string contactAddress { get; set; }
        [Column(TypeName = "int(11)")]
        public int leadTenantPersonId { get; set; }
        [Column(TypeName = "varchar(201)")]
        public string leadTenant { get; set; }
        [Column(TypeName = "int(11)")]
        public int? jointTenantPersonId { get; set; }
        [Column(TypeName = "varchar(201)")]
        public string jointTenant { get; set; }
        [Column(TypeName = "int(11)")]
        public int tenureTypeId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string tenureType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? startDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? terminationDate { get; set; }
        [Column(TypeName = "int(11)")]
        public int? terminationReasonId { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string terminationReason { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string updatedByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime updatedDT { get; set; }
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string createdByUserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createdDT { get; set; }
    }
}