// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHouse.Model.Core.Model
{
    public partial class vwuser
    {
        [Required]
        [Column(TypeName = "varchar(255)")]
        public string Id { get; set; }
        [Column(TypeName = "varchar(256)")]
        public string UserName { get; set; }
        [Column(TypeName = "varchar(256)")]
        public string Email { get; set; }
    }
}